Mahalakshmi Logistic Pvt Ltd/Controllers/AddChallanController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using Dapper;
using Mahalakshmi_Logistic_Pvt_Ltd.Models.ChallanRequest;

namespace Mahalakshmi_Logistic_Pvt_Ltd.Controllers
{
    public class AddChallanController : Controller
    {
         public SqlConnection SQLConn = new SqlConnection(ConfigurationManager.ConnectionStrings["dbconnection"].ConnectionString);

        // GET: AddChallan
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Challan_Request()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Challan_Request(Challan ch)
        {
            try
            {
                if (ch == null)
                {
                    if(!ModelState.IsValid)
                    {
                        string sqlQuerry = "insert into [dbo].[sale_challan] (Branch_id) values" +
                            "('" + ch.Branch_id+ "','\" + ch.Branch_id+\"','\" + ch.Branch_id+\"','\" + ch.Branch_id+\"','\" + ch.Branch_id+\"'  )";

                        return View();
                    }
                }


            }catch (Exception ex)
            {
                ViewBag.ChallanError =ex.Message; 
            }

            return View();
        }
        

        public ActionResult ChallanList()
        {
            try
            {
                string sqlQuerry = "Select * from [dbo].[sale_challan] ";

                var chList = SQLConn.Query<Challan>(sqlQuerry);
                List<Challan> list = chList.ToList();
                ViewBag.ChallanList = list;
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
            }
       
                return View();

        }



    }
}

Mahalakshmi Logistic Pvt Ltd/Controllers/Consignement_TrackingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Mahalakshmi_Logistic_Pvt_Ltd.Controllers
{
    public class Consignement_TrackingController : Controller
    {
        // GET: Consignement_Tracking



        public ActionResult Track_Consignment()
        {
            return View();
        }


    }
}

Mahalakshmi Logistic Pvt Ltd/Views/Consignement_Tracking/Track_Consignment.cshtml
@{
    ViewBag.Title = "Track_Consignment";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}


<div class="col-4">
    <h2 class="page-header">Consignment Tracking</h2>
</div>

<div class="col-4 pull-right">
 

    @*<a href="@Url.Action("Challan_Request", "AddChallan")" class="page-header"><i class="fa fa-plus-circle"></i>Add New</a>*@
</div>
<div class="row">
    <div class="panel panel-primary col-lg-12 col-md-12 col-sm-6">

        <div class="container m-3">
            <h5>Track Your Consignment</h5>

            <form id="consignmentForm" class="m-3 col-lg-12 col-md-12 col-sm-6">
                <label class="col-form-label-sm" for="vno">Enter CN No</label>
                <input class="form-control-sm" type="text" id="vno" name="vno" required>
                <button type="button" class="btn btn-primary btn-sm" onclick="trackConsignment()">Track</button>
            </form>
            @*<div class="table-responsive" style="height:40vh">*@
            <div id="result" class="col-lg-12 col-md-12 col-sm-6 "></div>
            @*</div>*@
        </div>
        </div>
</div>
<script>
    function trackConsignment() {
        var vno = document.getElementById("vno").value;

        // Construct the URL
        var url = "https://cntrack.lozics.in/Tracking.Ashx";

        // Construct the JSON payload
        var payload = {
            "interface": "RestAPI",
            "method": "GetConsignmentDetail",
            "parameters": { "VNO": vno },
            "token": "MLPL"
        };

        // Make the POST request
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(payload),
        })
            .then(response => response.json())
            .then(data => {
                // Display the result
                //console.log(data);
                displayConsignmentDetails(data);
            })
            .catch(error => {
                console.error('Error:', error);
                document.getElementById("result").innerHTML = "Error occurred. Please try again.";
            });
    }

    function displayConsignmentDetails(data) {
        var resultDiv = document.getElementById("result");
        resultDiv.innerHTML = ""; // Clear previous results
        resultDiv.style.width = "950px";
        // format the data for display
        var cnmtDetail = JSON.parse(data.Value).cnmtDetail;
        var movementDetail = JSON.parse(data.Value).movementDetail;
        var vehicleHireDetail = JSON.parse(data.Value).Table5;
        console.log(movementDetail)
        // Display consignment details

        // Add more details as needed
      
            //resultDiv.innerHTML += "<table class='table table-hover table-sm table-responsive'> <thead> <tr> <th scope='col'>Consignment No</th> <th scope='col'>Date</th>  <th scope='col'>Delivery At</th>  <th scope='col'>MODE</th>  </tr> </thead> <tbody> <tr> <td scope='row'>" + cnmtDetail[0].CNNO + "</td> <td>" + cnmtDetail[0].VDATE + "</td> <td> " + cnmtDetail[0].DELIVERYAT + " </td> <td> " + cnmtDetail[0].MODE + " </td>  </tr> </tbody> <tbody> <tr> <td colspan='2' scope='row'> <b> From </b> <br>" + cnmtDetail[0].CONSIGNOR + "<br>" + cnmtDetail[0].FROMSTATION + "</td> <td colspan='2'> <b> To </b> <br>" + cnmtDetail[0].CONSIGNEE + "<br>" + cnmtDetail[0].TOSTATION + "</td> </tr> <tr> <td colspan='4'><b>Statuts : </b>" + cnmtDetail[0].STATUS + "</td> </tr> </tbody> </table>";

            //resultDiv.innerHTML += "<table class='table table-hover  table-sm table-responsive'> <thead> <tr> <th scope='col'>Invoice No</th> <th scope='col'>Invoice Date</th> <th scope='col'> Item </th> <th scope='col'> Package </th>  <th scope='col'> Weight </th>  </tr> </thead> <tbody> <tr> <td scope='row'>" + cnmtDetail[0].INVOICENO + "</td> <td>" + cnmtDetail[0].INVOICEDATE + "</td> <td>" + cnmtDetail[0].ITEM + "</td> <td>" + cnmtDetail[0].PKGS + "</td>  <td>" + cnmtDetail[0].WEIGHT + "</td> </tr> </tbody> </table>";

        

        if (cnmtDetail != 0) {
            resultDiv.innerHTML += "<table class='table table-hover table-sm table-responsive'> <thead> <tr> <th scope='col'>Consignment No</th> <th scope='col'>Date</th>  <th scope='col'>Delivery At</th>  <th scope='col'>MODE</th>  </tr> </thead> <tbody> <tr> <td scope='row'>" + cnmtDetail[0].CNNO + "</td> <td>" + cnmtDetail[0].VDATE + "</td> <td> " + cnmtDetail[0].DELIVERYAT + " </td> <td> " + cnmtDetail[0].MODE + " </td>  </tr> </tbody> <tbody> <tr> <td colspan='2' scope='row'> <b> From </b> <br>" + cnmtDetail[0].CONSIGNOR + "<br>" + cnmtDetail[0].FROMSTATION + "</td> <td colspan='2'> <b> To </b> <br>" + cnmtDetail[0].CONSIGNEE + "<br>" + cnmtDetail[0].TOSTATION + "</td> </tr> <tr> <td colspan='4'><b>Statuts : </b>" + cnmtDetail[0].STATUS + "</td> </tr> </tbody> </table>";

            resultDiv.innerHTML += "<table class='table table-hover  table-sm table-responsive'> <thead> <tr> <th scope='col'>Invoice No</th> <th scope='col'>Invoice Date</th> <th scope='col'> Item </th> <th scope='col'> Package </th>  <th scope='col'> Weight </th>  </tr> </thead> <tbody> <tr> <td scope='row'>" + cnmtDetail[0].INVOICENO + "</td> <td>" + cnmtDetail[0].INVOICEDATE + "</td> <td>" + cnmtDetail[0].ITEM + "</td> <td>" + cnmtDetail[0].PKGS + "</td>  <td>" + cnmtDetail[0].WEIGHT + "</td> </tr> </tbody> </table>";
        }if (movementDetail[1]) {
            resultDiv.innerHTML += "<table class='table table-hover table-sm'> <thead> <tr> <th scope='col'>Vehicle Hire</th> <th scope='col'>Date</th> <th scope='col'>Manifest No</th> <th scope='col'>Date</th> <th scope='col'> Vehicle No </th> <th scope='col'> Status </th>  <th scope='col'> Weight </th>  </tr> </thead> <tbody> <tr> <td scope='row'>" + vehicleHireDetail[0].VHM_VNO + "</td> <td scope='row'>" + vehicleHireDetail[0].VHDATE + "</td> <td scope='row'>" + movementDetail[1].CNS_VNO + "</td> <td>" + movementDetail[1].VDATE + "</td> <td>" + movementDetail[1].VEHICLENO + "</td> <td>" + movementDetail[1].STATUS + "</td>  <td>" + cnmtDetail[0].WEIGHT + "</td> </tr> </tbody> </table>";


            //resultDiv.innerHTML += "<br>Vehicle Hire : " + vehicleHireDetail[0].VHM_VNO;

            //resultDiv.innerHTML += "<br>Manifest No : " + movementDetail[1].CNS_VNO;
            //resultDiv.innerHTML += "<br>Date : " + movementDetail[1].VDATE;
            //resultDiv.innerHTML += "<br>Vehicle No : " + movementDetail[1].VEHICLENO;
            //resultDiv.innerHTML += "<br>Status : " + movementDetail[1].STATUS;

        }

     

///*         Display movement details
//*/        resultDiv.innerHTML += "<b>Movement Details</b>";
//        for (var i = 0; i < movementDetail.length; i++) {
//          resultDiv.innerHTML += "<p><strong>Movement " + (i + 1) + ":</strong> " + movementDetail[i].CONSIGNEE + "</p>";
//       /*  Add more details as needed*/
//        }
    }
</script>