Mahalakshmi Logistic Pvt Ltd/Models/PartMaster/AddParts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mahalakshmi_Logistic_Pvt_Ltd.Models.PartMaster
{
    public class AddParts
    {
        public int Id { get; set; }
        public string Created_date { get; set; }    
        public string Category { get; set; }
        public string Part_number { get; set; }
        public string Hsn_number { get; set; }     
        public string Alias { get; set; }         
        public string Description { get; set; }
        public string Gst { get; set; }    
        public string Dimensions { get; set; }
        public string Rental_price { get; set; }
        public string Purchase_price { get; set;}
        public string Pocket_qty { get; set; }
        public string Gsm { get; set; }
        public string Color { get; set; }
        public string Thickness { get; set; }
        public string Weight { get; set; }  
        public string Volume_Weight { get; set; }
        public string Fresh_Stock { get; set; }
        public string Intransit_Stock { get; set; }
        public string Delivered_Stock { get; set; }
        public string Maintenance_Stock { get; set; }
        public string Scrap_Stock { get; set; }
        public string Stock_Alert { get; set; }
        public string Status { get; set; }
        public string Sale_Price { get; set; }

    }
}

Mahalakshmi Logistic Pvt Ltd/Controllers/PartMasterController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Dapper;
using Mahalakshmi_Logistic_Pvt_Ltd.Models.PartMaster;

namespace Mahalakshmi_Logistic_Pvt_Ltd.Controllers
{
    public class PartMasterController : Controller
    {
        public SqlConnection SqlConn = new SqlConnection(ConfigurationManager.ConnectionStrings["dbconnection"].ConnectionString);

        // GET: PartMaster
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateParts()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateParts(AddParts parts)
        {
            try
            {
                 
                
                string SqlQuerry = "insert into [master_parts_stocks] ([created_date],[category],[part_number],[hsn_number],[alias],[description],[gst],[dimensions],[rental_price],[purchase_price],[pocket_qty],[gsm],[color],[thickness],[weight],[volume_weight],[fresh_stock],[intransit_stock],[delivered_stock],[maintenance_stock],[scrap_stock],[stock_alert],[status],[sale_price]) values" +
                    "('"+parts.Created_date+"','"+parts.Category+"','"+parts.Part_number+"','"+parts.Hsn_number+"','"+parts.Alias+"','"+parts.Description+"','"+parts.Gst+"','"+parts.Dimensions+"','"+parts.Rental_price+"','"+parts.Purchase_price+"','"+parts.Pocket_qty+"','"+parts.Gsm+"','"+parts.Color+"','"+parts.Thickness+"','"+parts.Weight+"','"+parts.Volume_Weight+"','"+parts.Fresh_Stock+"','"+parts.Intransit_Stock+"','"+parts.Delivered_Stock+"','"+parts.Maintenance_Stock+ "','"+parts.Scrap_Stock+"','"+parts.Stock_Alert+"','"+parts.Status+"','"+parts.Sale_Price+"')";
                int qty = (int)(ViewData["Success"] = SqlConn.Execute(SqlQuerry));

                if (qty == 1)
                {
                    ViewBag.Maz = "Parts Created Successfully";
                }
                else
                {
                    ViewBag.error = "Oops Something Missing ! Please Check Details !!  ";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;  
            }
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> PartsListAsync()
        {
            try
            {
                if(ModelState.IsValid)
                {
                    string sqlQuerry = "Select * from [master_parts_stocks]";
                    var partsData = await SqlConn.QueryAsync<AddParts>(sqlQuerry);
                    List<AddParts> lists = partsData.ToList();
                    ViewBag.PartsList = lists;
                }
                else
                {
                    ViewBag.msz = "Parts List Empty!!";
                }
            }
            catch(Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }

            return View();
        }

        public async Task<ActionResult>EditParts(int id)
        {

            try
            {

                if (ModelState.IsValid)
                {
                    if(id != 0)
                    {
                        string sqlQuerry = "Select * from [master_parts_stocks] where id ='"+id+"' ";
                        var getById =await SqlConn.QueryAsync<AddParts>(sqlQuerry);
                        List<AddParts> lists = getById.ToList();
                        ViewBag.PartsList = lists;


                        ViewData["Success"]=await SqlConn.ExecuteAsync(sqlQuerry);
                       
                    }
                }

            }catch(Exception ex)
            {
                ViewBag.error = ex.Message;
            }

            return View();
        }
        [HttpPost]
        public async Task<ActionResult> EditParts(AddParts parts,  int id)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    if(parts != null)
                    {
                        if(id == parts.Id)
                        {
                            string sqlQuerry = "Update [master_parts_stocks] set ('"+parts.Created_date+"','"+parts.Category+"','"+parts.Part_number+"','"+parts.Hsn_number+"','"+parts.Alias+"','"+parts.Description+"','"+parts.Gst+"','"+parts.Dimensions+"','"+parts.Rental_price+"','"+parts.Purchase_price+"','"+parts.Pocket_qty+"','"+parts.Gsm+"','"+parts.Color+"','"+parts.Thickness+"','"+parts.Weight+"','"+parts.Volume_Weight+"','"+parts.Fresh_Stock+"','"+parts.Intransit_Stock+"','"+parts.Delivered_Stock+"','"+parts.Maintenance_Stock+"','"+parts.Scrap_Stock+"','"+parts.Stock_Alert+"','"+parts.Status+"','"+parts.Sale_Price+"') where id = '"+id+"' ";
                                  ViewData["Success"] = await SqlConn.ExecuteAsync(sqlQuerry);
                        }
                    }
                }

            }catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
            }



            return View();
        }


    }
}

Mahalakshmi Logistic Pvt Ltd/Views/PartMaster/CreateParts.cshtml
@*@model Mahalakshmi_Logistic_Pvt_Ltd.Models.PartMaster.AddParts*@
@{
    ViewBag.Title = "CreateParts";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<script>
    $(function () {
        var msz = @ViewData["Success"];

        if (msz == 1) {
            alert("New Part Added Successfully !! ");
        }

    })
    function onchangeDatemy() {
       /* var n = document.getElementById("#mycu");*/
        var cu = new Date().toLocaleDateString();
        return cu;
    }
     

</script>

<div class="col-lg-12">
    <h3 class="page-header"><i class="fa fa-user-plus"></i> Add Parts </h3>



    <span style="color:green">@ViewBag.Maz</span>


    <span style="color:red">@ViewBag.error </span>

    @if (@ViewBag.ErrorMessage != null)
    {
        foreach (var it in @ViewBag.ErrorMessage)
        {<span style="color:red">@it </span>}
    }



</div>
<!-- /.col-lg-12 -->
<!-- /.row -->
<div class="col-4 pull-right">
    <a href="@Url.Action("PartsListAsync","PartMaster")" class="page-header"><i class="fa fa-list"></i>Part List</a>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Parts Details
            </div>
            <div class="panel-body">
                <div class="row">
                    <form method="post">
                           <input type="date" name="created_date"  class="form-control" />
                        <div class="col-lg-6">
                            <div class="form-group input-group">

                                <span class="input-group-addon"><i class="fa fa-asterisk"></i> </span>
                                @*<input type="text" class="form-control badge-border" placeholder="User Code">*@
                                <select class="form-control" name="Category" required>
                                    <option selected>--Category--</option>
                                    <option value="PPIN">PPIN</option>
                                    <option value="CRT">CRT</option>
                                    <option value="WMP">WMP</option>
                                    <option value="MNT">MNT</option>
                                    <option value="MCM">MCM</option>
                                    <option value="RPB">RPB</option>
                                    <option value="WPL">WPL</option>
                                    <option value="PP BOX">PP BOX</option>
                                    <option value="PP Foldable Box">PP Foldable Box</option>
                                    <option value="FLC-1210">FLC-1210</option>
                                    <option value="FLC-128">FLC-128</option>
                                    <option value="FLC-1411">FLC-1411</option>
                                    <option value="FLC-1612">FLC-1612</option>
                                </select>


                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-edit"></i> </span>
                                <input type="text" class="form-control" name="part_number" placeholder="Equipment Id">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-map-marker"></i> </span>
                                <input type="text" class="form-control" name="hsn_number" placeholder="HSN Number">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-phone"></i> </span>
                                <input type="text" class="form-control" name="dimensions" placeholder="Size">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-envelope"></i> </span>
                                <input type="text" class="form-control" name="description" placeholder="Description">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-key"></i> </span>
                                <input type="text" class="form-control" placeholder="Weight(Kg)" name="weight">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-key"></i> </span>
                                <input type="text" class="form-control" placeholder="Alias" name="alias">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-angle-double-up"></i> </span>
                                <input type="text" class="form-control" placeholder="Volume Weight" name="volume_weight">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-rupee"></i> </span>
                                <input type="text" class="form-control" placeholder="Purchase_price" name="purchase_price">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-get-pocket"></i> </span>
                                <input type="text" class="form-control" placeholder="Pocket Qty" name="pocket_qty">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-sort-numeric-asc"></i> </span>
                                <input type="text" class="form-control" placeholder="GSM" name="gsm">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-bar-chart-o"></i> </span>
                                <input type="text" class="form-control" placeholder="Color" name="color">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-th-large"></i> </span>
                                <input type="text" class="form-control" placeholder="Thickness" name="thickness">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-warning"></i> </span>
                                <input type="text" class="form-control" placeholder="Stock Alert" name="stock_alert">
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-file-text"></i> </span>
                                <textarea type="text" class="form-control" placeholder="Description" name="description"></textarea>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="fa fa-star"></i> </span>
                                <select class="form-control" name="status">
                                    <option selected value="Active">Active</option>
                                    <option value="InActive">InActive</option>
                                </select>
                            </div>
                        </div>
                        <div align="center">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                            <button type="reset" class="btn btn-danger"><i class="fa fa-refresh"></i> Reset</button>
                        </div>
                    </form>
                        <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
               
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
    <!-- /.row -->

</div>

Mahalakshmi Logistic Pvt Ltd/Views/PartMaster/PartsListAsync.cshtml
@model Mahalakshmi_Logistic_Pvt_Ltd.Models.PartMaster.AddParts

@{
    ViewBag.Title = "PartsListAsync";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}


<div class="col-4">
    <h2 class="page-header">Part List</h2>
</div>
<div class="col-4 pull-right">
    <a href="@Url.Action("CreateParts", "PartMaster")" class="page-header"><i class="fa fa-plus-circle"></i>Add New</a>
</div>
<div class="row">
    <div class="panel panel-primary col-lg-12">

        <div class="table-responsive" style="height:400px">

            <table class="table">
                <thead style="background-color:dimgray;color:white;padding:1em;">

                    <tr class="bg-secondary">
                        <th>
                            Category
                        </th>
                        <th>
                            Equipment Id
                        </th>
                        <th>
                            Weight(KG)
                        </th>
                        <th>
                            Volume Weight
                        </th>
                        <th>
                            Price Per Unit
                        </th>
                        <th>
                            Pocket Quantity
                        </th>
                        <th>
                            GSM
                        </th>
                        <th>
                            Color
                        </th>
                        <th>
                            Thickness
                        </th>
                        <th>
                            Stock Alert
                        </th>
                        <th>
                            Alias
                        </th>
                        <th>Edit|Delete/View</th>
                    </tr>

                </thead>
                @foreach (var item in ViewBag.PartsList)
                {
                    <tbody>

                        <tr>
                            <td>
                                @item.Category
                            </td>
                            <td>
                                @item.Part_number
                            </td>
                            <td>
                                @item.Weight
                            </td>
                            <td>
                                @item.Volume_Weight
                            </td>
                            <td>
                                @item.Purchase_price
                            </td>
                            <td>
                                @item.Pocket_qty
                            </td>
                            <td>
                                @item.Gsm
                            </td>
                            <td>
                                @item.Color
                            </td>
                            <td>
                                @item.Thickness
                            </td>
                            <td>
                                @item.Stock_Alert
                            </td>
                            <td>
                                @item.Alias
                            </td>
                            <td>
                                <a href="@Url.Action("EditCustomer", "PartMaster", new { id = @item.Id })"><i class="fa fa-edit"></i></a> |
                                <a href="@Url.Action("DeleteCustomer","PartMaster", new { id = @item.Id })" style="color:red"><i class="fa fa-trash-o bg-danger "></i></a>
                                <a href="@Url.Action("Details","PartMaster", new { id = @item.Id })" style="color:deepskyblue"><i class="fa fa-eye-slash bg-primary "></i></a>

                            <td>
                        </tr>
                    </tbody>
                }


            </table>
        </div>

    </div>
</div>